-- 코드를 입력하세요
SELECT  F.CATEGORY,F.PRICE AS MAX_PRICE, F.PRODUCT_NAME FROM 
(SELECT CATEGORY C,MAX(PRICE) P 
FROM FOOD_PRODUCT
GROUP BY CATEGORY 
HAVING CATEGORY IN('식용유','과자','국','김치') 
)AS K , FOOD_PRODUCT F
WHERE K.C = F.CATEGORY AND K.P= F.PRICE
ORDER BY F.PRICE DESC


;